[package]
name = "eoa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
plotters = "0.3.5"
rand_distr = "0.4.3"
clap = { version = "4.4.7", features = ["derive"] }
